### ISSUE TITLE
Add Instructions Tab

### ISSUE THREAD

**Issue by yash-agarwal17** [yash-agarwal17/ComputerVision#1]
PoseNet runs with either a single-pose or multi-pose detection algorithm. The single person pose detector is faster and more accurate but requires only one subject present in the image. 

The output stride and image scale factor have the largest effects on accuracy/speed. A higher output stride results in lower accuracy but higher speed. A higher image scale factor results in higher accuracy but lower speed.

Add the instruction window giving users the the insructions so that they are in proper lighting and at appropriate distance from the webcam. This should come under the Skeletal section before loading the canvas.

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by yash-agarwal17** [comment]
@Rattlecode17sh  go on.

**Comment by Rattlecode17sh** [comment]
@opencodebot unclaim

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by yash-agarwal17** [comment]
@Rattlecode17sh do it this time.

**Comment by Rattlecode17sh** [comment]
@yash-agarwal17 i need one more day to figure out the problem. It's half complete but will take some time to solve
