### ISSUE TITLE
Add a modal at the loading of website.

### ISSUE THREAD

**Issue by yash-agarwal17** [yash-agarwal17/ComputerVision#10]

**Comment by nikolai6303** [comment]
@opencodebot claim

**Comment by yash-agarwal17** [comment]
Yes @nikolai6303 . Make suitable modal to load automatically at the starting of website

**Comment by Archies11** [comment]
Can I work on this?

**Comment by yash-agarwal17** [comment]
@Archies11  issue #13 is a similar one. You can try that.
