### ISSUE TITLE
Create a modal only for "Tilt your head to change color " section

### ISSUE THREAD

**Issue by yash-agarwal17** [yash-agarwal17/ComputerVision#13]
Create a modal only for the above section. Make button so that it can be reloaded. Name the button as instructions and place it near Start webcam button.

**Comment by neerajd007** [comment]
@yash-agarwal17 Can I work on this issue?

**Comment by Rattlecode17sh** [comment]
As there is no acticivity on this issue since past 8 days i want to give it a shot

**Comment by Archies11** [comment]
@yash-agarwal17 I was assigned this issue prior to @Rattlecode17sh 's comment, should I continue working on it?

**Comment by yash-agarwal17** [comment]
@Archies11 you can work on this.

**Comment by Rattlecode17sh** [comment]
@Archies11 you can solve this
