### ISSUE TITLE
Add button to stop Skeletal

### ISSUE THREAD

**Issue by yash-agarwal17** [yash-agarwal17/ComputerVision#2]
Right now the web cam starts on click of start webcam button. Make a stop button under the section Skeletal section to stop the webcam.

**Comment by Rattlecode17sh** [comment]
@yash-agarwal17  let me solve this issue

**Comment by HGOYAL015** [comment]
@opencode claim

**Comment by yash-agarwal17** [comment]
@HGOYAL015  Go ahead!

**Comment by HGOYAL015** [comment]
Sir please help me how to begin
