### ISSUE TITLE
Add CSS to Skeletal heading

### ISSUE THREAD

**Issue by yash-agarwal17** [yash-agarwal17/ComputerVision#3]

**Comment by Rattlecode17sh** [comment]
What changes are required??

**Comment by Rattlecode17sh** [comment]
I want to work on this

**Comment by yash-agarwal17** [comment]
@Rattlecode17sh  go ahead. Make it look like a proper project heading without appropriate fonts and positioning.

**Comment by Archies11** [comment]
Can we claim two issues of the same repo at a time? @yash-agarwal17

**Comment by yash-agarwal17** [comment]
@Archies11 , thanks for pointing. Marks will be awarded accordingly.
