### ISSUE TITLE
Add gradient background to Skeletal Section

### ISSUE THREAD

**Issue by yash-agarwal17** [yash-agarwal17/ComputerVision#9]
Add a gradient background to the whole skeletal section.

**Comment by neerajd007** [comment]
@yash-agarwal17 I want to work on this issue!

**Comment by yash-agarwal17** [comment]
@neerajd007 you can. I think you'll need to change the color schemes of canvas and menu also so that it matches the background. Make sure it looks good all together. Check if canvas is going without any background color as we'll now have the gradient background.

**Comment by neerajd007** [comment]
Sure Sir !

**Comment by yash-agarwal17** [comment]
@neerajd007  you doing this?

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by vishnuk7** [comment]
yash-agarwal17 can i work this?

**Comment by yash-agarwal17** [comment]
@vishnuk7 you can. Make sure it's good enough. Read above comments for clarification. Add the gradient background only to skeletal section and not to the whole website.

**Comment by yash-agarwal17** [comment]
@vishnuk7 you can add your own css files or containers if required. Make separate classes for them to avoid confusion.
